"""ADD USERNAME

Revision ID: 193b4e7ec8a9
Revises: 1aa506cab6ab
Create Date: 2025-11-04 10:27:14.105823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193b4e7ec8a9'
down_revision: Union[str, Sequence[str], None] = '1aa506cab6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('file_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('questions', 'file_id')
    # ### end Alembic commands ###
