"""Добавил подсчет точности игрока

Revision ID: ac2bec1e1f96
Revises: 193b4e7ec8a9
Create Date: 2025-12-28 14:31:53.478795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2bec1e1f96'
down_revision: Union[str, Sequence[str], None] = '193b4e7ec8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
