"""Удалил лишнии данные о подписке

Revision ID: c9b91b231f70
Revises: ac2bec1e1f96
Create Date: 2026-01-24 16:02:03.388219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b91b231f70'
down_revision: Union[str, Sequence[str], None] = 'ac2bec1e1f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'subscription_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_end', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
